### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [jdereg/java-util#35]
Hi
The following source files are without license headers:

./src/main/java/com/cedarsoftware/util/ProxyFactory.java

./src/test/java/com/cedarsoftware/util/TestByteUtilities.java
./src/test/java/com/cedarsoftware/util/TestDateUtilities.java
./src/test/java/com/cedarsoftware/util/TestExceptionUtilities.java
./src/test/java/com/cedarsoftware/util/TestHandshakeException.java
./src/test/java/com/cedarsoftware/util/TestInetAddressUnknownHostException.java
./src/test/java/com/cedarsoftware/util/TestProxyFactory.java
./src/test/java/com/cedarsoftware/util/TestStringUtilities.java
./src/test/java/com/cedarsoftware/util/TestUrlInvocationHandlerWhenExceptionsAreThrown.java
./src/test/java/com/cedarsoftware/util/TestUrlInvocationHandlerWithPlainReader.java

Please, confirm the licensing of code and/or content/s, and add license headers.

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by jdereg** [comment]
I added the missing copyright headers and pushed them.  The next release 1.25.0 will include them.  Already, you can see they have been added to the repo.
