### ISSUE TITLE
Why GraphComparator.Delta is not Serialized.

### ISSUE THREAD

**Issue by metlaivan** [jdereg/java-util#36]
I try to use your library for communicate client server via RMI, but GraphComparator.Delta isn't Serialized. Can you explain why it isn't Serialized?

**Comment by jdereg** [comment]
I did include your change to allow RMI support.

The 'Serializable' interface is old-school imho.  Using a serializer like json-io (one of my other projects), gson, etc. you can serialize any Java objects, not Java classes that have to be 'pre-marked' with a marker interface (anti-pattern).  I realize you may be in a situation where you have to use ObjectInputStream / ObjectOutputStream.  If you do not have to use them, then definitely take a look at a JSON based serializer like json-io or gson.

**Comment by jdereg** [comment]
Ivan - java-util 1.25.1 was released to Maven Central on Dec 4th which contains your changes.
