### ISSUE TITLE
Cannot use fastLookup hash using DeepHashCode

### ISSUE THREAD

**Issue by JasperTimm** [jdereg/java-util#40]
https://github.com/jdereg/java-util/blob/379899bb71f442966c87bdff1a187250269311a9/src/main/java/com/cedarsoftware/util/DeepEquals.java#L477

Unfortunately, hashCodes are not intended to be unique, so it's possible that two keys would have the same hash and the second will overwrite the first. In a Map with 110 entries using unique 4 char Strings, I found 4 keys with duplicate hashes.

At that point what you're really after is a unique id for each Object (key). This would fix the above problem but I just realised there is a more fundamental problem with the idea of trying to compare Maps in general: There might be cases where you consider two keys in a map to be deeply equal, but Java does not consider them equal, hence it's possible to have them both in the same Map. At that point, you're conflicting with the principle of the same key in a Map always resolving to the same value. Maybe at that point you can compare the Set of values the equal keys map to but that's skirting on the edges of what a Map really is...

**Comment by jdereg** [comment]
On inspection, that does indeed look like a bug.  I am looking into this and plan to release a fix this weekend.

**Comment by jdereg** [comment]
This issue has been fixed.  Unit tests were added that proved the issue.  Performance for comparing unordered Collections and Maps has been maintained. 

This is released in 1.33.0 on Maven Central.
