### ISSUE TITLE
deepEquals() could take another optional arg to allow differences to be spelled out

### ISSUE THREAD

**Issue by paul-hammant** [jdereg/java-util#41]
As people use deepEquals in unit testing, things are occasionally going to **not** be deep equals, and something better than assertTrue() is needed.  If not another arg, then whatever is needed to deliver assertDeepEquals(a,b) that'd throw exceptions that are helpful to debuggers :)

**Comment by jdereg** [comment]
java-util already has such support.  Use the GraphComparator class and write assertions about the returned Delta objects.

**Comment by paul-hammant** [comment]
The trick I've been using for a decade is:

```
XStream xs = new XStream();
assertEquals(xs.toXML(actual), xs.toXML(expected));
```

And I'm motivated to have least lines of code, so I may stick with that :)

**Comment by jdereg** [comment]
It would be trivial to add code that wrote back to the options map, the 'story' on what actually did not match.  For example, it knows if it is comparing primitives, Collections, Maps, etc, so in addition to "return false" when something does not match, DeepEquals could write to a 'REASON' key in the passed in options Map.  Initially, this could be the String description of what did not match, including showing the value of both items being compared.

Is that more like what you want?

**Comment by paul-hammant** [comment]
Sounds great, especially if you overrode toString() on that to aid the 'test failed' workflow :)

**Comment by jdereg** [comment]
I am making a new release of java-util soon, and will add this capability in that release.

**Comment by jdereg** [comment]
Actually, for now, it is better to use GraphUtilities.compare() to see "where" to graphs differ.  deepEquals() will give you the quick true / false answer.  If you need more information, use GraphUtilities.compare() to get the list of differences.

**Comment by paul-hammant** [comment]
XStream has many hundreds of round-trip test that take a scenario to XML and back again, then assert on the outcome. HashMap and HashSet are covered.
