### ISSUE TITLE
Question or Feature request: Compare complex objects

### ISSUE THREAD

**Issue by mburger81** [jdereg/java-util#43]
We try to use you GraphComparator to compare two complex objects each other. 

For a simple object it is working really good, but I'm not able to get it work with properties which are an List of other Complex Objects which could contain again a complex object.

Let me explain better, if we have for Example this object (we will represent it for simplicity by an json object):

    {
    	"id": 1,
    	"name": "Master1",
    	"details": [{
    		"id": 1,
    		"name": "Master1.Detail1"
    	}, {
    		"id": 2,
    		"name": "Master2.Detail2",
    		"subDetail": [{
    			"id1": 1,
    			"name": "Master2.Detail2.SubDetail1"
    		}]
    	}]
    }

In This Case if we change `name` in `SubDetail1` and compare old with new object we need also to be notified that the property in the third level of 3 complex objects changed.

Is this possible with you library? Can we do a workaround to get it work?

**Comment by jdereg** [comment]
I am planning on making a new release of java-util.  I will look into this issue.  It will either be a new test case, or an explanation detailing the current behavior, if it is correct.

**Comment by jdereg** [comment]
GraphCompare handles this situation as it is written.  It is cycle-aware (cycles will not lock it up), as well as 'shared reference' aware (really, the same cycle issue).

The indication when there is a mismatch in two graphs will be the first occurrence of the difference.
