### ISSUE TITLE
Vulnerability in log4j

### ISSUE THREAD

**Issue by Duvel** [jdereg/java-util#47]
You are using a version of log4j, that has a known vulnerability:
https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Aapache&cpe_product=cpe%3A%2F%3Aapache%3Alog4j&cpe_version=cpe%3A%2F%3Aapache%3Alog4j%3A2.5

Could you please update to a more recent version?

**Comment by Duvel** [comment]
I see now, that the vulnerability is in the dependency log4j and not log4j-api, which triggered our vulnerability scanner. Nevertheless probably still a good idea to upgrade.

**Comment by jdereg** [comment]
I updated java-util to log4j 2.13.1.
