### ISSUE TITLE
DeepEquals: issue for IGNORE_CUSTOM_EQUALS option

### ISSUE THREAD

**Issue by lipisak** [jdereg/java-util#69]
Hi,
I have found a possible issue in DeepEquals utility. It's possible to use the IGNORE_CUSTOM_EQUALS options (if you don't want to use custom equals implementation for specific classes). This option should be Set<String> as it's loaded from options Map on line 176 in DeepEquals utility. But if you look at usage of this set the input parameter of contains method is Class on line 361 (it always be false if any class should be "blacklisted").

Thx.
JS

**Comment by jdereg** [comment]
I reviewed and incorporated your changes - thank you for supplying a PR.  I am planning to release a patch release containing this change.

**Comment by jdereg** [comment]
Closing as fixed in upcoming 2.1.0 release.
