### ISSUE TITLE
Graph Comparator issue with Set order

### ISSUE THREAD

**Issue by guanlinzhou** [jdereg/java-util#77]
https://github.com/jdereg/java-util/issues/74

I believe this issue still persists when `GraphComparator::deepEquals` is used. Set comparisons are failing but UnorderedMap comparison with a dummy value succeed

**Comment by jdereg** [comment]
Tests have been added that verify that GraphComparator does not generate differences for when Sets are in different orders.  Using java-util 2.2.0, if you can generate a test case that demonstrates GraphComparator generating diffs when the Sets contain the same content but not in the same order, please share the code (ideally, a Junit).
